.gitignore, package.json, src/@types/@jitsi/rtcstats/rtcstats.d.ts, src/@types/@jitsi/rtcstats/trace-ws.d.ts, src/services/mediaService.tsx, src/store/actions/roomActions.tsx, src/store/middlewares/roomMiddleware.tsx, src/store/slices/roomSlice.tsx, src/store/slices/webrtcSlice.tsx, src/utils/types.tsx, yarn.lock
=> Add rtcstats and roomSessionId

src/components/me/Me.tsx, src/components/translated/translatedComponents.tsx, src/components/unmutealert/UnmuteAlert.tsx, src/components/volume/Volume.tsx, src/services/mediaService.tsx, src/store/actions/mediaActions.tsx
Added an alert when microphone is off and the user is speaking
=> Fixed #25: Added unmute alert

src/components/noiseslider/NoiseSlider.tsx, src/components/settingsdialog/advancedsettings/AdvancedAudioSettings.tsx, src/store/slices/settingsSlice.tsx
Created and added the NoiseSlider component for setting the noise threshold value (useful for voice activation feature)
=> Feature alignment - Added Noise slider in Advanced Audio Settings

src/components/settingsdialog/SettingsSelectors.tsx, src/components/settingsdialog/advancedsettings/AdvancedVideoSettings.tsx, src/store/middlewares/recordingMiddleware.tsx, src/store/slices/settingsSlice.tsx
Added the mime type selector for the video recorder
=> Feature alignment - Added mime types settings for recorder

src/components/topbar/TopBar.tsx, src/store/middlewares/roomMiddleware.tsx, src/store/slices/roomSlice.tsx
Added a meeting duration timer in the room. The needed room-server function are implemented by [PR #4](https://github.com/edumeet/edumeet-room-server/pull/4). The result is the following:
**Desktop**
**Mobile**
=> Added meeting duration timer

src/components/fullscreenvideo/FullscreenVideo.tsx, src/components/topbar/TopBar.tsx
Fixed one of the bugs mentioned in issue #42: the fullscreen video is no more partially covered by the topbar. Also, the top bar height has been fixed to 64px now.
=> Fullscreen video fix

public/config/config.example.js, src/components/settingsdialog/SettingsDialog.tsx, src/components/settingsdialog/advancedsettings/AdvancedSettings.tsx, src/components/translated/translatedComponents.tsx, src/store/middlewares/notificationMiddleware.tsx, src/store/middlewares/roomMiddleware.tsx, src/store/slices/notificationsSlice.tsx, src/store/slices/roomSlice.tsx, src/store/slices/settingsSlice.tsx, src/store/slices/uiSlice.tsx, src/store/store.tsx, src/utils/types.tsx
Added the sound alerts for notifications as requested in #49
=> Added sound alerts for notificartions

src/store/selectors.tsx, src/store/slices/peersSlice.tsx
Fixed the problem reported in #69.
=> Fixed multiple raised hand crash

src/App.tsx, src/components/precalldialog/PrecallDialog.tsx, src/store/slices/permissionsSlice.tsx
This PR solves the issue #87 as it is possible to see in the following image:
closes #87
=> Fixed showing login button when login disabled

src/components/devicechooser/AudioInputChooser.tsx
1. Added a separate state variable selectedAudioDevice to track the currently selected audio device before any changes are applied.
2. Modified the handleDeviceChange function to update the selectedAudioDevice when a new audio device is selected.
3. Updated the handleConfirm function to set the selectedAudioDevice to the appliedAudioDevice and apply the changes.
4. Revised the handleClose function to use the selectedAudioDevice when reverting the changes and to properly handle the cancellation action.
5. Updated the value prop of the DeviceChooser component to use the selectedAudioDevice instead of audioDevice.
6. Adjusted the dialog's onClose event handler to use handleClose function for proper cancellation functionality.
=> audio interface state fixed

src/components/controlbuttons/LoginButton.tsx, src/components/controlbuttons/LogoutButton.tsx, src/components/precalltitle/PrecallTitle.tsx, src/components/topbar/TopBar.tsx
closes #107 
This PR adds a LogoutButton component and use it in precall dialog and in top bar.
=> fix: add logout button

src/services/mediaService.tsx, src/store/middlewares/mediaMiddleware.tsx
This PR will enqueue error notifications on:
1.) No available media-nodes
2.) SocketTimeout error between room-server and active media-node.
=> feat: notify user about media-node error

package.json, src/services/signalingService.tsx, src/store/middlewares/signalingMiddleware.tsx, src/utils/RoomServerConnection.tsx, yarn.lock
closes #149 
This PR will move socket connection class to this repo and avoid dependency on edumeet-common for that.
=> move socket connection class to repo

checkmissing_translations.sh, src/components/devicechooser/DeviceChooser.tsx, src/components/genericdialog/GenericDialog.tsx, src/translations/cn.json, src/translations/cs.json, src/translations/de.json, src/translations/dk.json, src/translations/el.json, src/translations/en.json, src/translations/es.json, src/translations/fr.json, src/translations/hi.json, src/translations/hr.json, src/translations/hu.json, src/translations/it.json, src/translations/kk.json, src/translations/lv.json, src/translations/nb.json, src/translations/pl.json, src/translations/pt.json, src/translations/ro.json, src/translations/ru.json, src/translations/tr.json, src/translations/tw.json, src/translations/uk.json
Added 5 pixel to room name input box so logo is no longer mixing with the label.
Updated tranlsations that were not in the language files + created script to look for occurances. (also added some missing hu translations)
Update labels for media device chooser, it is no longer mixing with the shadow of the media device preview.
=> Fix small styling changes

src/App.tsx
https://github.com/edumeet/edumeet-client/issues/181
=> Fix camera is not release after left

src/components/managementservice/groups/Groups.tsx, src/components/managementservice/role/Role.tsx, src/views/management/Management.tsx
Fix ui, and hide parameters that cannot be assigned (at creation).
=> Feat mgmt fixes

package.json, src/components/breakoutrooms/ListBreakoutRoom.tsx, src/components/draganddrop/DragAndDropContextWrapper.tsx, src/components/draganddrop/DraggableWrapper.tsx, src/components/draganddrop/DroppableWrapper.tsx, src/components/draganddrop/GhostObject.tsx, src/components/participantlist/ParticipantList.tsx, src/store/actions/roomActions.tsx, yarn.lock
add drag and drop feature for participants and breakout rooms
=> Add Drag and Drop functionality to Breakout Rooms

src/components/managementservice/groups/GroupRole.tsx, src/components/managementservice/groups/GroupUser.tsx, src/components/managementservice/role/Role.tsx, src/components/managementservice/rules/Rule.tsx, src/components/managementservice/tenants/TenantOAuth.tsx, src/components/managementservice/tenants/TenatnFQDN.tsx, src/store/actions/managementActions.tsx, src/utils/types.tsx, src/views/management/Management.tsx
Added rule system.
Become: 
- TenantAdmin
- TenantOwner
- Super admin
- Group member
To stop user creation:
- Assert error if user satisfies condition
Added name parameter so user name can be displayed. (can be configured for TenantOAuth)
Added parameter to end session (not just remove token for application).
Small fixes for geting and listing API results.
=> Feat mgmt rules

src/components/controlbuttonsbar/ControlButtonsBar.tsx, src/components/participantlist/ListMe.tsx
Restore functionality which got lost during #223:
- Bring back raise hand button for mobile devices on ListMe in participant list
- Consider `raiseHandEnabled`
=> Fix raise hand on mobile

src/index.tsx
=> feat: set page title from config
